# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: ssh deploy
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@54f2361d27c4ab86ea0a2560836444d123e63cd8
      uses: easingthemes/ssh-deploy@v2.1.0
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.YUN}}
        # Remote host
        REMOTE_HOST: "148.70.32.97"
        # Remote user
        REMOTE_USER: "root"
        # Remote port
        REMOTE_PORT: "22"
        # Source directory
        SOURCE: "dist/"
        # Target directory
        TARGET: "/www/wwwroot/supermall/"
